name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hellow from github actions"
      - name: Print Bye
        run: echo "Bye bye..hasta la vista"
    
